{% set name = "matplotlib-venn" %}
{% set version = "0.11.5" %}
{% set bundle = "zip" %}
{% set hash_type = "sha256" %}
{% set hash_val = "be017a6821bce410db3314099649f1a0fcf4c0fbf7be0c1190b102187988838f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - matplotlib_venn

about:
  home: https://github.com/konstantint/matplotlib-venn
  license: MIT
  license_family: MIT
  summary: 'Functions for plotting area-proportional two- and three-way Venn diagrams in matplotlib.'
  dev_url: https://github.com/konstantint/matplotlib-venn

extra:
  recipe-maintainers:
    - pmlandwehr
