{% set name = "matplotlib-venn" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matplotlib-venn-{{ version }}.tar.gz
  sha256: 6f2b07a03e9bb5a62de2f32f965216739e175176f9d654dd19e7af2c22ec36e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pytest
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - matplotlib_venn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/konstantint/matplotlib-venn
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Functions for plotting area-proportional two- and three-way Venn diagrams in matplotlib.
  dev_url: https://github.com/konstantint/matplotlib-venn

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
