{% set name = "matplotlib-venn" %}
{% set version = "0.11.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matplotlib-venn-{{ version }}.tar.gz
  sha256: 90d0cfb279c5dbbdf7dfd722c0e2515a37f535e949bcad174483bc777e372e65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pytest
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - matplotlib_venn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/konstantint/matplotlib-venn
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Functions for plotting area-proportional two- and three-way Venn diagrams in matplotlib.
  dev_url: https://github.com/konstantint/matplotlib-venn

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
